version: '3.1'

services:

    mongodb:
        image: mongo
        restart: always
        volumes: 
            - ./data:/data/db
        
    backend:
        build: .
        restart: always
        depends_on:
            - mongodb
        ports:
            - 8080:8080

    frontend:
        image: "everythingplay/moscityhack-front"
        restart: always
        ports:
            - 80:80